### ISSUE TITLE
SSLEOFError

### ISSUE THREAD

**Issue by nikilster** [django-push-notifications/django-push-notifications#159]
Getting this error when trying to send a lot of push notifications:

SSLEOFError 
EOF occurred in violation of protocol (_ssl.c:590)

Stack Trace: 

https://www.dropbox.com/s/qej6neungq2ujjf/Screenshot%202015-06-10%2012.46.53.png?dl=0

**Comment by Alp-Phone** [comment]
Have you tried sending them in bulk?

**Comment by nikilster** [comment]
Ohh good idea - earlier we had different text in the messages, now they are the same so we can do in bulk!  Thanks!

Do you have any ideas on what is causing the error?

**Comment by tub216** [comment]
this is a ssl version problem. after I fix ssl version to tlsv1, I works.

http://stackoverflow.com/questions/14102416/python-requests-requests-exceptions-sslerror-errno-8-ssl-c504-eof-occurred

sock = ssl.wrap_socket(sock, ssl_version=ssl.PROTOCOL_TLSv1, certfile=certfile)

**Comment by jleclanche** [comment]
SSLv3 is not supported.

**Comment by YuriHeupa** [comment]
I'm getting this error, even sending in bulk, i'm using the latest version

**Comment by nikilster** [comment]
We're still getting this error - any ideas?

**Comment by Afnarel** [comment]
Hi!

We are also having this issue since we updated for the latest version with Python 3.4 and Django 1.8.
Can you please reopen this issue?

**Comment by jleclanche** [comment]
I doubt this is related to SSLv3, can you open a new issue with a full stack trace please

**Comment by Afnarel** [comment]
Ok I will open a new issue. I agree that this is probably not related to SSLv3 since the call to ssl.wrap_socket forces TLSv1.

**Comment by nikilster** [comment]
We're still seeing this - seems like sometimes APNS closes the connection?

**Comment by davidchiles** [comment]
I'm seeing this problem as well.

`SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)`

```
File "/Users/david/.virtualenvs/pythonbrew/lib/python2.7/site-packages/push_notifications/apns.py", line 58, in _apns_create_socket_to_push
    return _apns_create_socket((SETTINGS["APNS_HOST"], SETTINGS["APNS_PORT"]))
  File "/Users/david/.virtualenvs/pythonbrew/lib/python2.7/site-packages/push_notifications/apns.py", line 52, in _apns_create_socket
    sock.connect(address_tuple)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 844, in connect
    self._real_connect(addr, False)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 835, in _real_connect
    self.do_handshake()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 808, in do_handshake
```

**Comment by nikilster** [comment]
Getting a ton of these SSLEOF errors - we are sending a lot of push notifications in 1 API call - and this error happens a lot.

**Comment by eyscode** [comment]
Same error here with Python 2.7.10 and the latest version of django-push-notifications (1.4.1) and  Django (1.9.2) on updated Ubuntu 15.10. Any solution?

**Comment by jleclanche** [comment]
I'm reopening since Google seems to lead directly here and nobody opened a new issue.

**Comment by jdcaram-djed** [comment]
All of a sudden, on Friday, April 8, we started getting the "EOF occurred in violation of protocol" error when our code tries to create a socket: "with closing(apns._apns_create_socket_to_push()) as socket:"

Both in Staging (Sandbox) and PROD.  We tried creating new certificates this morning - but that hasn't resolved anything.  The weird part is that it's about 50/50 when a Push Notification is going to work - or we get the EOF error.  And we can't repro locally debugging either....

**Comment by eyscode** [comment]
I had this problem on Ubuntu 15.10 which was my production server and had the same project in another server with Ubuntu 14.04 but everything was fine. So I thought it was a issue with SSL on that version of Ubuntu so I changed to 14.04, and till today I haven't have the problem again.

**Comment by jleclanche** [comment]
We since switched to pyapns which means this probably either doesn't happen anymore, or if it does, it's an upstream issue.
