### ISSUE TITLE
Having a "WebPush" device --does it make sense?

### ISSUE THREAD

**Issue by alexbarcelo** [django-push-notifications/django-push-notifications#335]
I started to use this project before fully understanding what is a WebPush and what is a Push. Given that I wanted to perform WebPush for Android Chrome browsers, I was focused on the GCM stuff and forgot to teach myself about WebPush and its requirements --mainly the required encryption mechanisms.

The current GCM device here is somewhat compatible with Chrome WebPush browsers, but because they lack encryption it is not possible to send information from the server to the client (at least, that is what I understood from [google](https://developers.google.com/web/updates/2016/03/web-push-encryption) and [mozilla](https://developer.mozilla.org/en-US/docs/Web/API/Push_API/Using_the_Push_API), sorry for my ignorance).

In the end I rolled my own library (my requirements were very modest) using the [`pywebpush`](https://github.com/web-push-libs/pywebpush/) which provides the encryption requirements for the WebPush I wanted. However, I was thinking that maybe a WebPushDevice would be a "good feature" to `django-push-notifications`.

Does it make sense? Or it would clutter the library and it is not the same philosophy as the current devices?

**Comment by alexbarcelo** [comment]
I was completely sure to have checked "WebPush" and found nothing, and now I am seeing something somewhat WebPush related in #316.

Sorry. Should I close this?

**Comment by jamaalscarlett** [comment]
If you want to submit a PR go for it.  #316 does not actually have any code that does anything in it.

**Comment by alexbarcelo** [comment]
I see that this project has no external requirements (aside Django).

Would it be sensible to have the `WebPushDevice` and everything in place but perform `import pywebpush` in the `send_message` method and complain there? Or should there be a global (settings?) flag to enable WebPush *before* the data model and that stuff? 

I would lean towards complaining in the `send_message` method --as there may be deployments that have a Celery task in a worker node with more installed packages, and the `pywebpush` is not required in anything else.

Because there must be encryption, doing it pure python doesn't seem reasonable. But I am not sure what would be better regarding requirements and usage, and I don't want to prepare the PR with the wrong perspective.

**Comment by jamaalscarlett** [comment]
@alexbarcelo Yes that's the way the tastypie and django-rest-framework features work

**Comment by goinnn** [comment]
@alexbarcelo @jamaalscarlett I want to do this feature. I am going to do a pull request with  WebPushDevice feature. If you have pywebpush installed.

I have been doing several tests and now I can send push to Chrome or Firefox without problems.

And of course I write a documentation. There  is very little documentation about it. And very very bad and confused.

**Comment by jamaalscarlett** [comment]
@goinnn go for it.
