### ISSUE TITLE
AttributeError: 'module' object has no attribute 'OP_NO_COMPRESSION'

### ISSUE THREAD

**Issue by cesarbecerra** [django-push-notifications/django-push-notifications#397]
Why did i get this error?
my settings are like this

`PUSH_NOTIFICATIONS_SETTINGS = {
    "APNS_CERTIFICATE": os.path.join(BASE_DIR, 'apns.p8'),
    "APNS_TOPIC": "com.mx.......",
}`

**Comment by jleclanche** [comment]
Try Python 3 maybe? Sounds like a Python 2 on OSX issue.

**Comment by cesarbecerra** [comment]
my whole project is in python 2 😢

**Comment by cesarbecerra** [comment]
well i resolved that problem but now am stuck with another bug

sl_context.load_cert_chain(cert_file)
SSLError: [SSL] PEM lib (_ssl.c:2699)

**Comment by shigmas** [comment]
If you're talking about JWT authorization tokens, then no. This library depends on apns2, which doesn't support it. I've submitted a PR on that library, and then I'll submit a PR here. So, it's in the foreseeable...ish future.

**Comment by vrgimael** [comment]
@cesarbecerra how did you solve this problem? I'm stuck with the same thing now...

Thanks!

**Comment by cesarbecerra** [comment]
@vrgimael you need to upgrade your OPENSSL library with BREW and then you need to link it to python

**Comment by jamaalscarlett** [comment]
@cesarbecerra is your issue resolved?  Can we close out this issue?
