### ISSUE TITLE
'application_id' on GCMDeviceSerializer

### ISSUE THREAD

**Issue by jksimoniii** [django-push-notifications/django-push-notifications#436]
https://github.com/jleclanche/django-push-notifications/commit/78586d383816261a940227516244c5f750a07bb6 addresses this issue and has been merged into master (https://github.com/jleclanche/django-push-notifications/pull/401).  When will this be built and included in the latest pip package?

**Comment by jksimoniii** [comment]
Also, it does not look like this will be available in https://github.com/jleclanche/django-push-notifications/releases/tag/1.5.0

**Comment by jleclanche** [comment]
I'm about to be unavailable for 3 weeks but I can make a new release when I get back.
