### ISSUE TITLE
django-push-notifications forces me to use Django 1.11.7

### ISSUE THREAD

**Issue by Yungbubu** [django-push-notifications/django-push-notifications#441]
Hi All,

I'm having trouble installing this package.

When I do: 

`pip install django-push-notifications`

pip automatically uninstall my Django version (1.9.5) and installs Django 1.11.7 which obviously I don't want.

I then reinstalled Django 1.9.5 and ended up with this error:

`pkg_resources.ContextualVersionConflict: (Django 1.9.5 (/Users/John/anaconda/lib/python3.5/site-packages), Requirement.parse('Django>=1.10'), {'django-push-notifications'})`

Also tried with Django 1.9, same error: 

`pkg_resources.ContextualVersionConflict: (Django 1.9 (/Users/John/anaconda/lib/python3.5/site-packages), Requirement.parse('Django>=1.10'), {'django-push-notifications'})`

I really don't understand, this package is supposed to support Django 1.9 right ?

My Setup:

Mac OS X 10.12.6
pip 8.1.1 & 9.0.1 (tried both)
django-push-notifications 1.5.0
Django 1.9.5 & 1.9 (tried both)
Python 3.5

Thanks for your help!

**Comment by jleclanche** [comment]
The latest version of DPN is not compatible with Django <1.10:

https://github.com/django-push-notifications/django-push-notifications/blob/master/setup.cfg#L29

I recommend you upgrade to 1.11. The path from 1.9 is very easy and it's a LTS.

Compatibility with previous versions will not be restored, so I'm closing this. Hope this helps.

**Comment by Yungbubu** [comment]
I'm not trying to use Django <1.10

I want to use Django 1.9.5 or 1.9. 

I think you misread my message ^^

**Comment by jleclanche** [comment]
1.9 is older than 1.10...

**Comment by Yungbubu** [comment]
Owww  got it now ^^. I'm sorry I was really confused about the version numbers.
