### ISSUE TITLE
Compatibility issue with Django 2.0

### ISSUE THREAD

**Issue by RoystonDmello** [django-push-notifications/django-push-notifications#446]
user.is_authenticated() does not work with Django 2.0

**Comment by odinuge** [comment]
Hi,

This is fixed in #445. Should be a part of the next release.

**Comment by matt-dalton** [comment]
Any timeframe on when we can expect the release? We are currently pretty stuck until this comes out. Thanks!

**Comment by jleclanche** [comment]
@matt-dalton the latest version was released a couple of days ago.
